-- MySQL Script generated by MySQL Workbench
-- Tue Dec 22 12:37:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema makowskim
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema makowskim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `makowskim` DEFAULT CHARACTER SET utf8 ;
USE `makowskim` ;

-- -----------------------------------------------------
-- Table `makowskim`.`Klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makowskim`.`Klient` (
  `idKlienta` INT NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `NrTel` INT(9) NULL,
  PRIMARY KEY (`idKlienta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makowskim`.`Rezerwacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makowskim`.`Rezerwacja` (
  `idRezerwacji` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NULL,
  `Godzina` TIME NULL,
  `idKlienta` INT NOT NULL,
  PRIMARY KEY (`idRezerwacji`),
  INDEX `fk_Rezerwacja_Klient_idx` (`idKlienta` ASC) VISIBLE,
  CONSTRAINT `fk_Rezerwacja_Klient`
    FOREIGN KEY (`idKlienta`)
    REFERENCES `makowskim`.`Klient` (`idKlienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makowskim`.`Stolik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makowskim`.`Stolik` (
  `NrStolika` INT NOT NULL AUTO_INCREMENT,
  `LiczbaMiejsc` VARCHAR(45) NULL,
  PRIMARY KEY (`NrStolika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makowskim`.`RezerwacjaStolikow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makowskim`.`RezerwacjaStolikow` (
  `Rezerwacja_idRezerwacji` INT NOT NULL,
  `Stolik_NrStolika` INT NOT NULL,
  PRIMARY KEY (`Rezerwacja_idRezerwacji`, `Stolik_NrStolika`),
  INDEX `fk_Rezerwacja_has_Stolik_Stolik1_idx` (`Stolik_NrStolika` ASC) VISIBLE,
  INDEX `fk_Rezerwacja_has_Stolik_Rezerwacja1_idx` (`Rezerwacja_idRezerwacji` ASC) VISIBLE,
  CONSTRAINT `fk_Rezerwacja_has_Stolik_Rezerwacja1`
    FOREIGN KEY (`Rezerwacja_idRezerwacji`)
    REFERENCES `makowskim`.`Rezerwacja` (`idRezerwacji`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezerwacja_has_Stolik_Stolik1`
    FOREIGN KEY (`Stolik_NrStolika`)
    REFERENCES `makowskim`.`Stolik` (`NrStolika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makowskim`.`Pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makowskim`.`Pracownik` (
  `idPracownik` INT NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `DataUr` DATE NULL,
  `Pesel` INT(11) NULL,
  `Stanowisko` ENUM('kucharz', 'kelner', 'recepcjonista') NULL,
  PRIMARY KEY (`idPracownik`),
  UNIQUE INDEX `Pesel_UNIQUE` (`Pesel` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
